spring.application.name=SpringBoot_With_AWS_CICd
spring.datasource.url=jdbc:mysql://localhost:3306/blog_app_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
server.port=9090
